[workspace]
resolver = "3"
members = [
  "crates/brick",
  "crates/ui-assets",
  "crates/brick_macro",
  "crates/content",
  "crates/transport",
  "crates/transport-ws",
  "crates/fluxen",
  "crates/ui_dixous",
  "crates/ui_dixous_macro",
  "crates/ui_leptos",
  "crates/ui_leptos_macro",
]

[workspace.dependencies]
anyhow = "1.0.102"
brick = { path = "crates/brick", version = "^0.1.0" }
content = { path = "crates/content", version = "^0.1.0" }
transport = { path = "crates/transport", version = "^0.1.0" }
ui-assets = { path = "crates/ui-assets", version = "^0.1.0" }
transport-ws = { path = "crates/transport-ws", version = "^0.1.0" }
ciborium = "0.2"
chrono = { version = "0.4.44", features = ["serde"] }
dioxus = { version = "0.7.9" }
futures = "0.3.32"
gloo-net = "0.7.0"
indexmap = { version = "2.14.0", features = ["serde"] }
indoc = "2.0.7"
itertools = "0.14.0"
js-sys = "0.3.98"
maplit = "1.0.2"
markdown = "1.0.0"
minijinja = { version = "2.19.0", features = ["loader"] }
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
quote = "1.0.45"
regex = "1"
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.149"
syn = { version = "2.0.117", features = ["extra-traits", "full"] }
tracing = "0.1.44"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.121"
web-sys = "0.3.98"

leptos = { version = "0.8", features = ["csr"] }
send_wrapper = "0.6"
console_error_panic_hook = "0.1"

[workspace.package]
rust-version = "1.88.0"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
