[package]
name = "ui_leptos"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
anyhow.workspace = true
brick = { workspace = true, features = ["classify", "merge", "ops", "render"] }
console_error_panic_hook.workspace = true
content.workspace = true
futures.workspace = true
gloo-net.workspace = true
itertools.workspace = true
js-sys.workspace = true
leptos.workspace = true
markdown.workspace = true
message.workspace = true
minijinja.workspace = true
send_wrapper.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-wasm.workspace = true
ui_leptos_macro = { path = "../ui_leptos_macro" }
wasm-bindgen.workspace = true
web-sys.workspace = true
