[package]
name = "accrete"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars = { version = "1.2.1", optional = true, features = ["chrono04"] }
regex = { workspace = true, optional = true }
accrete_macro = { path = "../accrete_macro", optional = true }

[dev-dependencies]
accrete = { path = ".", features = ["ops", "classify"] }
serde_json.workspace = true

[features]
schema = ["dep:schemars"]
classify = ["dep:regex", "dep:accrete_macro"]
ops = ["dep:accrete_macro"]
