[package]
name = "stage"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stage"
path = "src/main.rs"

[dependencies]
accrete = { workspace = true, features = ["classify", "ops", "template"] }
content = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "fs"] }
tokio-tungstenite = "0.24"
rustyline = "14"
clap = { version = "4", features = ["derive"] }
axum = { version = "0.8", features = ["ws"] }
kdl = "6.7.1"
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "tokio"] }
http-body-util = "0.1"
serde_yaml = "0.9"
