[package]
name = "ui_dixous"
version = "0.1.0"
authors = ["nash <fj0rd@qq.com>"]
edition = "2024"

[dependencies]
anyhow.workspace = true
brick = { workspace = true, features = ["classify", "dioxus", "merge", "ops", "template"] } #unified
chrono.workspace = true
content.workspace = true
message.workspace = true
ciborium.workspace = true
dioxus.features = ["macro", "web"]
dioxus.workspace = true
futures.workspace = true
gloo-net.workspace = true
indoc.workspace = true
itertools.workspace = true
js-sys.workspace = true
maplit.workspace = true
markdown.workspace = true
minijinja.workspace = true
serde.features = ["derive", "serde_derive"]
serde.workspace = true
serde_json.workspace = true
tracing-wasm.workspace = true
ui_dixous_macro = { path = "../ui_dixous_macro" }
web-sys.workspace = true

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
